import { inter } from "@/app/fonts";
import "./globals.css";
import FlagContact from "@/components/FlagContact";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <FlagContact /> */}
        <Navbar />

        {children}
      </body>
    </html>
  );
}
